# ABOUTME: SQLAlchemy model for investigation tasks generated by the Synthesis Agent.
# ABOUTME: Tasks link back to hypotheses, contradictions, and gaps that originated them.

from datetime import datetime
from uuid import UUID

from sqlalchemy import DateTime, ForeignKey, Index, String, Text, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class InvestigationTask(Base):
    """
    An investigation task generated by the Synthesis Agent.

    Tasks are actionable items derived from hypotheses, contradictions,
    and gaps. Each task has a type indicating the investigation action
    needed and a priority level for triage.
    """

    __tablename__ = "investigation_tasks"
    __table_args__ = (Index("idx_investigation_tasks_case_id", "case_id"),)

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    case_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("cases.id", ondelete="CASCADE"),
        nullable=False,
    )
    workflow_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(
        String(300),
        nullable=False,
        comment="Short description of the task",
    )
    description: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Detailed explanation of what needs to be done",
    )
    task_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="resolve_contradiction, obtain_evidence, verify_hypothesis, "
        "follow_up_interview, document_retrieval, external_research, "
        "cross_reference, expert_consultation",
    )
    priority: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default="medium",
        comment="low, medium, high, or critical",
    )
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default="pending",
        comment="pending, in_progress, completed, or dismissed",
    )
    source_hypothesis_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("case_hypotheses.id", ondelete="SET NULL"),
        nullable=True,
        comment="Hypothesis that originated this task",
    )
    source_contradiction_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("case_contradictions.id", ondelete="SET NULL"),
        nullable=True,
        comment="Contradiction that originated this task",
    )
    source_gap_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("case_gaps.id", ondelete="SET NULL"),
        nullable=True,
        comment="Gap that originated this task",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("now()"),
        nullable=False,
    )

    # Relationships
    case = relationship("Case")
